In [ ]:
import polars as pl
import fastplotlib as fpl

In [ ]:
df = pl.read_csv("./Data.csv")

df

shape: (683, 11)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬─────────┬───────┐
│ Sample     ┆ Clump      ┆ Uniformity ┆ Uniformity ┆ … ┆ Bland      ┆ Normal    ┆ Mitoses ┆ Class │
│ code       ┆ Thickness  ┆ of Cell    ┆ of Cell    ┆   ┆ Chromatin  ┆ Nucleoli  ┆ ---     ┆ ---   │
│ number     ┆ ---        ┆ Size       ┆ Shape      ┆   ┆ ---        ┆ ---       ┆ i64     ┆ i64   │
│ ---        ┆ i64        ┆ ---        ┆ ---        ┆   ┆ i64        ┆ i64       ┆         ┆       │
│ i64        ┆            ┆ i64        ┆ i64        ┆   ┆            ┆           ┆         ┆       │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═════════╪═══════╡
│ 1000025    ┆ 5          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1002945    ┆ 5          ┆ 4          ┆ 4          ┆ … ┆ 3          ┆ 2         ┆ 1       ┆ 2     │
│ 1015425    ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1016277    ┆ 6          ┆ 8          ┆ 8          ┆ … ┆ 3          ┆ 7         ┆ 1       ┆ 2     │
│ 1017023    ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1017122    ┆ 8          ┆ 10         ┆ 10         ┆ … ┆ 9          ┆ 7         ┆ 1       ┆ 4     │
│ 1018099    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1018561    ┆ 2          ┆ 1          ┆ 2          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1033078    ┆ 2          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 5       ┆ 2     │
│ 1033078    ┆ 4          ┆ 2          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1035283    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1036172    ┆ 2          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1041801    ┆ 5          ┆ 3          ┆ 3          ┆ … ┆ 4          ┆ 4         ┆ 1       ┆ 4     │
│ 1043999    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1044572    ┆ 8          ┆ 7          ┆ 5          ┆ … ┆ 5          ┆ 5         ┆ 4       ┆ 4     │
│ 1047630    ┆ 7          ┆ 4          ┆ 6          ┆ … ┆ 4          ┆ 3         ┆ 1       ┆ 4     │
│ 1048672    ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1049815    ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1050670    ┆ 10         ┆ 7          ┆ 7          ┆ … ┆ 4          ┆ 1         ┆ 2       ┆ 4     │
│ 1050718    ┆ 6          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1054590    ┆ 7          ┆ 3          ┆ 2          ┆ … ┆ 5          ┆ 4         ┆ 4       ┆ 4     │
│ 1054593    ┆ 10         ┆ 5          ┆ 5          ┆ … ┆ 7          ┆ 10        ┆ 1       ┆ 4     │
│ 1056784    ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1059552    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1065726    ┆ 5          ┆ 2          ┆ 3          ┆ … ┆ 3          ┆ 6         ┆ 1       ┆ 4     │
│ 1066373    ┆ 3          ┆ 2          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1066979    ┆ 5          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1067444    ┆ 2          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1070935    ┆ 1          ┆ 1          ┆ 3          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1070935    ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1071760    ┆ 2          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1072179    ┆ 10         ┆ 7          ┆ 7          ┆ … ┆ 7          ┆ 4         ┆ 3       ┆ 4     │
│ 1074610    ┆ 2          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1075123    ┆ 3          ┆ 1          ┆ 2          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1079304    ┆ 2          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1080185    ┆ 10         ┆ 10         ┆ 10         ┆ … ┆ 8          ┆ 9         ┆ 1       ┆ 4     │
│ 1081791    ┆ 6          ┆ 2          ┆ 1          ┆ … ┆ 7          ┆ 1         ┆ 1       ┆ 2     │
│ 1084584    ┆ 5          ┆ 4          ┆ 4          ┆ … ┆ 5          ┆ 6         ┆ 1       ┆ 4     │
│ 1091262    ┆ 2          ┆ 5          ┆ 3          ┆ … ┆ 7          ┆ 5         ┆ 1       ┆ 4     │
│ 1099510    ┆ 10         ┆ 4          ┆ 3          ┆ … ┆ 6          ┆ 5         ┆ 2       ┆ 4     │
│ 1100524    ┆ 6          ┆ 10         ┆ 10         ┆ … ┆ 7          ┆ 3         ┆ 3       ┆ 4     │
│ 1102573    ┆ 5          ┆ 6          ┆ 5          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 4     │
│ 1103608    ┆ 10         ┆ 10         ┆ 10         ┆ … ┆ 8          ┆ 10        ┆ 1       ┆ 4     │
│ 1103722    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 2       ┆ 2     │
│ 1105257    ┆ 3          ┆ 7          ┆ 7          ┆ … ┆ 4          ┆ 8         ┆ 1       ┆ 4     │
│ 1105524    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1106095    ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1106829    ┆ 7          ┆ 8          ┆ 7          ┆ … ┆ 3          ┆ 8         ┆ 2       ┆ 4     │
│ 1108370    ┆ 9          ┆ 5          ┆ 8          ┆ … ┆ 2          ┆ 1         ┆ 5       ┆ 4     │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …       ┆ …     │
│ 1319609    ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1323477    ┆ 1          ┆ 2          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1324572    ┆ 5          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 2         ┆ 1       ┆ 2     │
│ 1324681    ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1325159    ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1326892    ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1330361    ┆ 5          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1333877    ┆ 5          ┆ 4          ┆ 5          ┆ … ┆ 3          ┆ 6         ┆ 1       ┆ 2     │
│ 1334015    ┆ 7          ┆ 8          ┆ 8          ┆ … ┆ 7          ┆ 2         ┆ 3       ┆ 4     │
│ 1334667    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1339781    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1339781    ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 13454352   ┆ 1          ┆ 1          ┆ 3          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1345452    ┆ 1          ┆ 1          ┆ 3          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1345593    ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1347749    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1347943    ┆ 5          ┆ 2          ┆ 2          ┆ … ┆ 1          ┆ 1         ┆ 2       ┆ 2     │
│ 1348851    ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1350319    ┆ 5          ┆ 7          ┆ 4          ┆ … ┆ 7          ┆ 10        ┆ 3       ┆ 4     │
│ 1350423    ┆ 5          ┆ 10         ┆ 10         ┆ … ┆ 7          ┆ 10        ┆ 1       ┆ 4     │
│ 1352848    ┆ 3          ┆ 10         ┆ 7          ┆ … ┆ 7          ┆ 4         ┆ 1       ┆ 4     │
│ 1353092    ┆ 3          ┆ 2          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1354840    ┆ 2          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1354840    ┆ 5          ┆ 3          ┆ 2          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1355260    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1365075    ┆ 4          ┆ 1          ┆ 4          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1365328    ┆ 1          ┆ 1          ┆ 2          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1368267    ┆ 5          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1368273    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1368882    ┆ 2          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1369821    ┆ 10         ┆ 10         ┆ 10         ┆ … ┆ 10         ┆ 10        ┆ 7       ┆ 4     │
│ 1371026    ┆ 5          ┆ 10         ┆ 10         ┆ … ┆ 5          ┆ 6         ┆ 3       ┆ 4     │
│ 1371920    ┆ 5          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 2         ┆ 1       ┆ 2     │
│ 466906     ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 466906     ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 534555     ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 536708     ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 566346     ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 3         ┆ 1       ┆ 2     │
│ 603148     ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 654546     ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 8       ┆ 2     │
│ 654546     ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 695091     ┆ 5          ┆ 10         ┆ 10         ┆ … ┆ 4          ┆ 4         ┆ 1       ┆ 4     │
│ 714039     ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 763235     ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 2       ┆ 2     │
│ 776715     ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 841769     ┆ 2          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 888820     ┆ 5          ┆ 10         ┆ 10         ┆ … ┆ 8          ┆ 10        ┆ 2       ┆ 4     │
│ 897471     ┆ 4          ┆ 8          ┆ 6          ┆ … ┆ 10         ┆ 6         ┆ 1       ┆ 4     │
│ 897471     ┆ 4          ┆ 8          ┆ 8          ┆ … ┆ 10         ┆ 4         ┆ 1       ┆ 4     │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴─────────┴───────┘

In [19]:
df.describe()

shape: (9, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬──────────┐
│ statistic  ┆ Sample    ┆ Clump     ┆ Uniformit ┆ … ┆ Bland     ┆ Normal    ┆ Mitoses  ┆ Class    │
│ ---        ┆ code      ┆ Thickness ┆ y of Cell ┆   ┆ Chromatin ┆ Nucleoli  ┆ ---      ┆ ---      │
│ str        ┆ number    ┆ ---       ┆ Size      ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64      │
│            ┆ ---       ┆ f64       ┆ ---       ┆   ┆ f64       ┆ f64       ┆          ┆          │
│            ┆ f64       ┆           ┆ f64       ┆   ┆           ┆           ┆          ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪══════════╡
│ count      ┆ 683.0     ┆ 683.0     ┆ 683.0     ┆ … ┆ 683.0     ┆ 683.0     ┆ 683.0    ┆ 683.0    │
│ null_count ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0      ┆ 0.0      │
│ mean       ┆ 1.0767e6  ┆ 4.442167  ┆ 3.150805  ┆ … ┆ 3.445095  ┆ 2.869693  ┆ 1.603221 ┆ 2.699854 │
│ std        ┆ 620644.04 ┆ 2.820761  ┆ 3.065145  ┆ … ┆ 2.449697  ┆ 3.052666  ┆ 1.732674 ┆ 0.954592 │
│            ┆ 7655      ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│ min        ┆ 63375.0   ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0      ┆ 2.0      │
│ 25%        ┆ 877943.0  ┆ 2.0       ┆ 1.0       ┆ … ┆ 2.0       ┆ 1.0       ┆ 1.0      ┆ 2.0      │
│ 50%        ┆ 1.171795e ┆ 4.0       ┆ 1.0       ┆ … ┆ 3.0       ┆ 1.0       ┆ 1.0      ┆ 2.0      │
│            ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│ 75%        ┆ 1.238777e ┆ 6.0       ┆ 5.0       ┆ … ┆ 5.0       ┆ 4.0       ┆ 1.0      ┆ 4.0      │
│            ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│ max        ┆ 1.3454352 ┆ 10.0      ┆ 10.0      ┆ … ┆ 10.0      ┆ 10.0      ┆ 10.0     ┆ 4.0      │
│            ┆ e7        ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴──────────┘

In [20]:
df.shape

(683, 11)

In [21]:
df.glimpse()

Rows: 683
Columns: 11
$ Sample code number          <i64> 1000025, 1002945, 1015425, 1016277, 1017023, 1017122, 1018099, 1018561, 1033078, 1033078
$ Clump Thickness             <i64> 5, 5, 3, 6, 4, 8, 1, 2, 2, 4
$ Uniformity of Cell Size     <i64> 1, 4, 1, 8, 1, 10, 1, 1, 1, 2
$ Uniformity of Cell Shape    <i64> 1, 4, 1, 8, 1, 10, 1, 2, 1, 1
$ Marginal Adhesion           <i64> 1, 5, 1, 1, 3, 8, 1, 1, 1, 1
$ Single Epithelial Cell Size <i64> 2, 7, 2, 3, 2, 7, 2, 2, 2, 2
$ Bare Nuclei                 <i64> 1, 10, 2, 4, 1, 10, 10, 1, 1, 1
$ Bland Chromatin             <i64> 3, 3, 3, 3, 3, 9, 3, 3, 1, 2
$ Normal Nucleoli             <i64> 1, 2, 1, 7, 1, 7, 1, 1, 1, 1
$ Mitoses                     <i64> 1, 1, 1, 1, 1, 1, 1, 1, 5, 1
$ Class                       <i64> 2, 2, 2, 2, 2, 4, 2, 2, 2, 2

In [22]:
df = df.unique()

In [30]:
duplicate_code_numbers = df.group_by(
    pl.col("Sample code number")
).len().filter(
    pl.col('len') > 1
).select(
    pl.col('Sample code number')
).to_series()

duplicate_code_numbers.sort()

shape: (38,)
Series: 'Sample code number' [i64]
[
	385103
	411453
	493452
	560680
	654546
	695091
	734111
	769612
	798429
	822829
	897471
	1017023
	1033078
	1061990
	1070935
	1105524
	1114570
	1115293
	1116192
	1143978
	1158247
	1168736
	1171710
	1173347
	1174057
	1182404
	1198641
	1212422
	1238777
	1240603
	1276091
	1277792
	1293439
	1299596
	1299924
	1320077
	1339781
	1354840
]

In [ ]:
df_duplicate_by_code_number = df.filter(
    pl.col('Sample code number').is_in(duplicate_code_numbers.implode()) 
).sort(pl.col('Sample code number')).head( 98)
df_duplicate_by_code_number

shape: (83, 11)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬─────────┬───────┐
│ Sample     ┆ Clump      ┆ Uniformity ┆ Uniformity ┆ … ┆ Bland      ┆ Normal    ┆ Mitoses ┆ Class │
│ code       ┆ Thickness  ┆ of Cell    ┆ of Cell    ┆   ┆ Chromatin  ┆ Nucleoli  ┆ ---     ┆ ---   │
│ number     ┆ ---        ┆ Size       ┆ Shape      ┆   ┆ ---        ┆ ---       ┆ i64     ┆ i64   │
│ ---        ┆ i64        ┆ ---        ┆ ---        ┆   ┆ i64        ┆ i64       ┆         ┆       │
│ i64        ┆            ┆ i64        ┆ i64        ┆   ┆            ┆           ┆         ┆       │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═════════╪═══════╡
│ 385103     ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 385103     ┆ 5          ┆ 1          ┆ 2          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 411453     ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 411453     ┆ 5          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 493452     ┆ 4          ┆ 1          ┆ 2          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 493452     ┆ 1          ┆ 1          ┆ 3          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 560680     ┆ 3          ┆ 1          ┆ 2          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 560680     ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 654546     ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 654546     ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 8       ┆ 2     │
│ 695091     ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 695091     ┆ 5          ┆ 10         ┆ 10         ┆ … ┆ 4          ┆ 4         ┆ 1       ┆ 4     │
│ 734111     ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 734111     ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 769612     ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 769612     ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 798429     ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 798429     ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 822829     ┆ 8          ┆ 10         ┆ 10         ┆ … ┆ 10         ┆ 10        ┆ 10      ┆ 4     │
│ 822829     ┆ 7          ┆ 6          ┆ 4          ┆ … ┆ 9          ┆ 5         ┆ 3       ┆ 4     │
│ 897471     ┆ 4          ┆ 8          ┆ 6          ┆ … ┆ 10         ┆ 6         ┆ 1       ┆ 4     │
│ 897471     ┆ 4          ┆ 8          ┆ 8          ┆ … ┆ 10         ┆ 4         ┆ 1       ┆ 4     │
│ 1017023    ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1017023    ┆ 6          ┆ 3          ┆ 3          ┆ … ┆ 3          ┆ 5         ┆ 3       ┆ 2     │
│ 1033078    ┆ 2          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 5       ┆ 2     │
│ 1033078    ┆ 4          ┆ 2          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1061990    ┆ 1          ┆ 1          ┆ 3          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1061990    ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1070935    ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1070935    ┆ 1          ┆ 1          ┆ 3          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1105524    ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1105524    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1114570    ┆ 2          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 2         ┆ 1       ┆ 2     │
│ 1114570    ┆ 5          ┆ 3          ┆ 3          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1115293    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1115293    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1116192    ┆ 5          ┆ 1          ┆ 2          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1116192    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1143978    ┆ 5          ┆ 2          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1143978    ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1158247    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1158247    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1168736    ┆ 5          ┆ 6          ┆ 6          ┆ … ┆ 3          ┆ 6         ┆ 1       ┆ 4     │
│ 1168736    ┆ 10         ┆ 10         ┆ 10         ┆ … ┆ 8          ┆ 8         ┆ 8       ┆ 4     │
│ 1171710    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 3         ┆ 1       ┆ 2     │
│ 1171710    ┆ 6          ┆ 5          ┆ 4          ┆ … ┆ 7          ┆ 8         ┆ 3       ┆ 4     │
│ 1173347    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1173347    ┆ 8          ┆ 3          ┆ 3          ┆ … ┆ 3          ┆ 2         ┆ 1       ┆ 2     │
│ 1174057    ┆ 1          ┆ 1          ┆ 2          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1174057    ┆ 4          ┆ 2          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1182404    ┆ 4          ┆ 2          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1182404    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1182404    ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1182404    ┆ 5          ┆ 1          ┆ 4          ┆ … ┆ 3          ┆ 2         ┆ 1       ┆ 2     │
│ 1182404    ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1182404    ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1198641    ┆ 10         ┆ 10         ┆ 6          ┆ … ┆ 4          ┆ 3         ┆ 2       ┆ 4     │
│ 1198641    ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1212422    ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1212422    ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1238777    ┆ 6          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1238777    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1240603    ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1240603    ┆ 2          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1276091    ┆ 5          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 2         ┆ 1       ┆ 2     │
│ 1276091    ┆ 6          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1276091    ┆ 1          ┆ 3          ┆ 1          ┆ … ┆ 2          ┆ 2         ┆ 1       ┆ 2     │
│ 1276091    ┆ 2          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1276091    ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1277792    ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1277792    ┆ 5          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1293439    ┆ 3          ┆ 2          ┆ 2          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1293439    ┆ 6          ┆ 9          ┆ 7          ┆ … ┆ 4          ┆ 2         ┆ 1       ┆ 2     │
│ 1299596    ┆ 2          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1299596    ┆ 6          ┆ 6          ┆ 6          ┆ … ┆ 7          ┆ 6         ┆ 2       ┆ 4     │
│ 1299924    ┆ 3          ┆ 2          ┆ 2          ┆ … ┆ 4          ┆ 2         ┆ 1       ┆ 2     │
│ 1299924    ┆ 5          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1320077    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1320077    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1339781    ┆ 1          ┆ 1          ┆ 1          ┆ … ┆ 2          ┆ 1         ┆ 1       ┆ 2     │
│ 1339781    ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1354840    ┆ 5          ┆ 3          ┆ 2          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 1354840    ┆ 2          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴─────────┴───────┘